version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::634317178490:user/streaming-dev"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::634317178490:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-5RXC0QMPKLE0"
cloudformation_execution_role = "arn:aws:iam::634317178490:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-E8A4DOM75NJO"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-14tqou20n5mjw"
image_repository = ""
region = "us-east-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::634317178490:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-5RXC0QMPKLE0""
cloudformation_execution_role = "arn:aws:iam::634317178490:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-1BCQUKZWL5H3Q"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-11nwloyb8e67f"
image_repository = ""
region = "us-east-1"
